
nginx:
  image: cyberdojofoundation/nginx
  links:
    - "web:cyberdojo_web"
  ports:
    - "80:80"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

web:
  command: rails server --environment=${CYBER_DOJO_RAILS_ENV}
  environment:
    - CYBER_DOJO_LANGUAGES_ROOT=${CYBER_DOJO_LANGUAGES_ROOT}
    - CYBER_DOJO_EXERCISES_ROOT=${CYBER_DOJO_EXERCISES_ROOT}
    - CYBER_DOJO_CACHES_ROOT=${CYBER_DOJO_CACHES_ROOT}
    - CYBER_DOJO_KATAS_ROOT=${CYBER_DOJO_KATAS_ROOT}
    - CYBER_DOJO_RUNNER_CLASS=${CYBER_DOJO_RUNNER_CLASS}
    - CYBER_DOJO_KATAS_CLASS=${CYBER_DOJO_KATAS_CLASS}
    - CYBER_DOJO_SHELL_CLASS=${CYBER_DOJO_SHELL_CLASS}
    - CYBER_DOJO_DISK_CLASS=${CYBER_DOJO_DISK_CLASS}
    - CYBER_DOJO_LOG_CLASS=${CYBER_DOJO_LOG_CLASS}
    - CYBER_DOJO_GIT_CLASS=${CYBER_DOJO_GIT_CLASS}
  image: cyberdojofoundation/web
  ports:
    - "3000:3000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${CYBER_DOJO_KATAS_ROOT}:${CYBER_DOJO_KATAS_ROOT}:rw
    - /tmp:/tmp:rw

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# The cyber-dojo script uses this file to find out the
# service names. It assumes the service name (eg web) is the
# tag name for the associated docker image (eg cyberdojofoundation/web)
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Variable-substition happens in docker-compose yml files
# such as this one, but *not* in env_file:'s
# Since I use variable-substitution in my environment
# I don't use an env_file:
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# I originally used a data-container for tmp/
# However, in the avatar's test docker-run I could not find a way
# to limit access only to its sub-folder of tmp/.
